//
// CardIOBundle.h
//
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY.
//
// To make changes, please either regenerate the file
// or update the generator (and submit a pull request
// with your fix!), as appropriate.
//
// Generated by command: `python baler.py assets/ Classes/ --overwrite-delay 0 -z -c CardIOBundle`
//

#import <UIKit/UIKit.h>

@interface CardIOBundle : NSObject

/// Get the CardIOBundle instance.
/// Expands and saves the bundle to the filesystem on first invocation.
+ (CardIOBundle *)sharedInstance;

/// Analogous to UIImage's +imageNamed:
- (UIImage *)imageNamed:(NSString *)name;

/// Use as you would any NSBundle
- (NSBundle *)NSBundle;

#if BALER_DEBUG
- (BOOL)passesSelfTest:(NSError **)error;
#endif

@end